"use strict";
exports.__esModule = true;
var person_1 = require("./person");
var service_1 = require("./service");
var service1 = new service_1.Service('PersonService');
var service2 = new service_1.Service('TokenService');
var service3 = new service_1.Service('AuthService');
// const p = new Person();
// console.log(p.getInfo());
// const p1 = new Person();
// console.log(p1.getInfo());
// const p2 = new Person();
// console.log(p2.getInfo());
var p = new person_1.Person(service1);
console.log(p.getInfo());
var p1 = new person_1.Person(service2);
console.log(p1.getInfo());
var p2 = new person_1.Person(service3);
console.log(p2.getInfo());
